### ISSUE TITLE
OMPyton ModelicaSystem setParameters() error message is missing quote characters and has typo

### ISSUE THREAD

**Issue by mjschuh** [OpenModelica/OpenModelica#11111]
### Description

Python OMPyton ModelicaSystem setParameters() error message is missing quote characters and <code>False</code> is not
capitalized. 

### Steps to Reproduce

Here is a model that can be used to display the error message.
```
# cat HelloWorld.mo
model HelloWorld "Model"
  Real x(start=1, fixed = true);
  parameter Real a = 1;       // Changable parameter
  Real y[N];
  parameter Integer N = 2;    // Structural parameter
  final parameter Real b = 3; // Final parameter
protected
  parameter Real c = 4;       // Protected parameter
public
  parameter Real d = 2*a;     // Evaluated parameter

  model M
    parameter Real e = 5;     // Changable parameter
  end M;
  M m(e=d);                   // Non-constant binding of e
equation
  der(x) = a*b*c*d*x;
  for i in 1:N loop
    y[i] = time;
  end for;
end HelloWorld;
```
Load the model and run it.  This works fine.
```
mschuh@ARDWG0121101002:~/Training/omshell$ python3
Python 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from OMPython import ModelicaSystem
>>> mod=ModelicaSystem("./HelloWorld.mo","HelloWorld",["Modelica"])
>>> mod.getSimulationOptions()
{'startTime': '0', 'stopTime': '1', 'stepSize': '0.002', 'tolerance': '1e-06', 'solver': 'dassl', 'outputFormat': 'mat'}
>>> mod.setSimulationOptions(["outputFormat=csv","stepSize=0.1"])
>>> mod.getSimulationOptions()
{'startTime': '0', 'stopTime': '1', 'stepSize': '0.1', 'tolerance': '1e-06', 'solver': 'dassl', 'outputFormat': 'csv'}
>>> mod.simulate(resultfile="HelloWorld_N2_res.csv")
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.
>>> mod.getParameters()
{'a': '1.0', 'b': '3.0', 'c': '4.0', 'd': None, 'm.e': None, 'N': '2'}
```
Trying to set the N parameter generates the error message.
```
>>> mod.setParameters(["N=8"])
| info |  setParameters() failed : It is not possible to set the following signal "N", It seems to be structural, final, protected or evaluated or has a non-constant binding, use sendExpression(setParameterValue(HelloWorld, N, 8), parsed=false) and rebuild the model using buildModel() API
```

First off, thank you very much for the very helpful error message above!!!  

When I use the recommended text from the error message above, an error message is generated.  Adding quote symbols before and after the <code>setParameterValue</code> call helps.  Capitalizing <code>False</code> is also needed for the recommended command to work properly. 
```
>>> mod.sendExpression(setParameterValue(HelloWorld, N, 8), parsed=false)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'setParameterValue' is not defined
>>> mod.sendExpression("setParameterValue(HelloWorld, N, 8)", parsed=false)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'false' is not defined
```
### Expected Behavior
Here is what works for changing a parameter that is structural, final, protected or evaluated, or has a non-constant binding.  The new parameter is not used until the <code>buildModel()</code> call has completed.
```
>>> mod.sendExpression("setParameterValue(HelloWorld, N, 8)", parsed=False)
'Ok\n'
>>> mod.getParameters()
{'a': '1.0', 'b': '3.0', 'c': '4.0', 'd': None, 'm.e': None, 'N': '2'}
>>> mod.buildModel()
>>> mod.getParameters()
{'a': '1.0', 'b': '3.0', 'c': '4.0', 'd': None, 'm.e': None, 'N': '8'}
>>> mod.simulate(resultfile="HelloWorld_N4_res.csv")
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.
```
The simulation results files show that setting <code>N</code> to 8 worked.
```
mschuh@ARDWG0121101002:~/Training/omshell$ cat HelloWorld_N2_res.csv
"time","x","der(x)","y[1]","y[2]"
0,1,96,0,0
0.1,14765.19482835879,1417458.703522444,0.1,0.1
0.2,218011911.7191462,20929143525.03804,0.2,0.2
0.3,3219002342374.568,309024224867958.5,0.3,0.3
0.4,4.75294008871961e+16,4.562822485170825e+18,0.4,0.4
0.5,7.017839026568625e+20,6.73712546550588e+22,0.5,0.5
0.6,1.036202065183123e+25,9.947539825757981e+26,0.6,0.6
0.7,1.529979137876618e+29,1.468779972361553e+31,0.7,0.7
0.8,2.259053734936325e+33,2.168691585538872e+35,0.8,0.8
0.9,3.335551233999685e+37,3.202129184639697e+39,0.9,0.9
1,4.925027662574612e+41,4.728026556071627e+43,1,1
1,4.925027662574612e+41,4.728026556071627e+43,1,1

mschuh@ARDWG0121101002:~/Training/omshell$ cat HelloWorld_N4_res.csv
"time","x","der(x)","y[1]","y[2]","y[3]","y[4]","y[5]","y[6]","y[7]","y[8]"
0,1,96,0,0,0,0,0,0,0,0
0.1,14765.19482835879,1417458.703522444,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
0.2,218011911.7191462,20929143525.03804,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
0.3,3219002342374.568,309024224867958.5,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
0.4,4.75294008871961e+16,4.562822485170825e+18,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
0.5,7.017839026568625e+20,6.73712546550588e+22,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
0.6,1.036202065183123e+25,9.947539825757981e+26,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.6
0.7,1.529979137876618e+29,1.468779972361553e+31,0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.7
0.8,2.259053734936325e+33,2.168691585538872e+35,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8
0.9,3.335551233999685e+37,3.202129184639697e+39,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9
1,4.925027662574612e+41,4.728026556071627e+43,1,1,1,1,1,1,1,1
1,4.925027662574612e+41,4.728026556071627e+43,1,1,1,1,1,1,1,1
```
### Version and OS

mschuh@ARDWG0121101002:\~/Training/omshell$ omc --version
OpenModelica 1.22.0\~dev-263-gfae4e48

mschuh@ARDWG0121101002:~/Training/omshell$ uname -a
Linux ARDWG0121101002 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by casella** [comment]
@arun3688 could you please fix this?
