### ISSUE TITLE
OMEdit crashes on close with animation window and messages browser

### ISSUE THREAD

**Issue by anotheruserofgithub** [OpenModelica/OpenModelica#11692]
### Description

https://github.com/OpenModelica/OpenModelica/pull/11627 introduced a bug when closing OMEdit while an animation window is active in the plotting perspective and the messages browser is visible.

### Steps to Reproduce

1. Open OMEdit
2. Go to the plotting perspective
3. Insert a new animation window
4. Keep the messages browser open
5. Quit OMEdit (either via menu, shortcut, or closing the window)
6. OMEdit window closes but a crash popup appears shortly afterwards

### Expected Behavior

OMEdit does not crash on close.

### Version and OS

 - OpenModelica Version: v1.23.0-dev commit 82a6c4c60094549188729c1676646999a7893240
 - OS: Ubuntu 18.04 64-bit

### Additional Context

Debugging with GDB using this command
```shell
gdb -iex "set auto-load safe-path /" -iex "handle SIGXCPU SIG33 SIG35 SIG36 SIG37 SIG38 SIGPWR nostop noprint" ./build/bin/OMEdit
```
produces the following backtrace.

<details>
<summary>Backtrace</summary>

```
Thread 1 "OMEdit" received signal SIGSEGV, Segmentation fault.
#0  0x00007fffed4e19a7 in QMutex::lock() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x0000555555a49f09 in QMutexLocker::QMutexLocker(QBasicMutex*) (this=0x7fffffffa328, m=0x70) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h:200
#2  0x0000555555a49d0f in MessagesWidget::showPendingMessages() (this=0x0) at Modeling/MessagesWidget.cpp:644
#3  0x0000555555d6a663 in ViewerWidget::paintGL() (this=0x55555abc34e0) at Animation/ViewerWidget.cpp:149
#4  0x0000555555d6a5fd in ViewerWidget::paintEvent(QPaintEvent*) (this=0x55555abc34e0) at Animation/ViewerWidget.cpp:130
#5  0x00007fffeeff5038 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x0000555555d6d46f in ViewerWidget::event(QEvent*) (this=0x55555abc34e0, event=0x7fffffffa700) at Animation/ViewerWidget.cpp:541
#7  0x00007fffeefb683c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007fffeefbe104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007fffed6c88a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fffeefee18a in QWidgetPrivate::sendPaintEvent(QRegion const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007fffef015cca in QOpenGLWidget::resizeEvent(QResizeEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007fffeeff5be2 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x0000555555d6d46f in ViewerWidget::event(QEvent*) (this=0x55555abc34e0, event=0x7fffffffaac0) at Animation/ViewerWidget.cpp:541
#14 0x00007fffeefb683c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007fffeefbe104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007fffed6c88a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007fffeefecf39 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007fffeefedca0 in QWidget::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007fffeefd65b3 in QWidgetItem::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007fffeefd0a55 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007fffeefd1637 in QGridLayout::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007fffeefd2a88 in QLayoutPrivate::doResize(QSize const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007fffeefb680a in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007fffeefbe104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007fffed6c88a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007fffeefecf39 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007fffeefedca0 in QWidget::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007fffeeff497f in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007fffeeff7203 in QWidget::qt_metacall(QMetaObject::Call, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007fffef0964f5 in QFrame::qt_metacall(QMetaObject::Call, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007fffed4c72c7 in QPropertyAnimation::updateCurrentValue(QVariant const&) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007fffed4c1bf8 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007fffed4c2e2d in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007fffed4c83da in QPropertyAnimation::updateState(QAbstractAnimation::State, QAbstractAnimation::State) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007fffed4bfafc in QAbstractAnimation::start(QAbstractAnimation::DeletionPolicy) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007fffef0a0bc3 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007fffef0e0860 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007fffef110260 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007fffef112bbe in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007fffeefd2a88 in QLayoutPrivate::doResize(QSize const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007fffeefb680a in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#42 0x00007fffeefbe104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#43 0x00007fffed6c88a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#44 0x00007fffeefecf39 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#45 0x00007fffeefedca0 in QWidget::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#46 0x00007fffeefd65b3 in QWidgetItem::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#47 0x00007fffeefcc6f0 in QBoxLayout::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x00007fffeefd2a88 in QLayoutPrivate::doResize(QSize const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007fffeefb680a in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#50 0x00007fffeefbe104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#51 0x00007fffed6c88a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x00007fffeefecf39 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#53 0x00007fffeefed50b in QWidget::resize(QSize const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#54 0x00007fffef119e75 in QMdiArea::resizeEvent(QResizeEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007fffeeff5be2 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#56 0x00007fffef09644e in QFrame::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#57 0x00007fffef11d34d in QMdiArea::viewportEvent(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007fffed6c858c in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#59 0x00007fffeefb6815 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#60 0x00007fffeefbe104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#61 0x00007fffed6c88a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#62 0x00007fffeefecf39 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#63 0x00007fffeefedca0 in QWidget::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#64 0x00007fffef09dcae in QAbstractScrollAreaPrivate::layoutChildren_helper(bool*, bool*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#65 0x00007fffef09e04a in QAbstractScrollAreaPrivate::layoutChildren() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#66 0x00007fffef09f486 in QAbstractScrollArea::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#67 0x00007fffef11d5fb in QMdiArea::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#68 0x00007fffeefb683c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#69 0x00007fffeefbe104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#70 0x00007fffed6c88a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#71 0x00007fffeefecf39 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#72 0x00007fffeefedca0 in QWidget::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#73 0x00007fffeefd2a88 in QLayoutPrivate::doResize(QSize const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#74 0x00007fffeefd3b19 in QLayout::activate() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#75 0x00007fffeefb680a in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#76 0x00007fffeefbe104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#77 0x00007fffed6c88a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#78 0x00007fffeefecf39 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#79 0x00007fffeefedca0 in QWidget::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#80 0x00007fffeefd65b3 in QWidgetItem::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#81 0x00007fffeefcc6f0 in QBoxLayout::setGeometry(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#82 0x00007fffeefd2a88 in QLayoutPrivate::doResize(QSize const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#83 0x00007fffeefd3b19 in QLayout::activate() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#84 0x00007fffeeff4b37 in QWidget::setVisible(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#85 0x0000555555a08958 in MainWindow::messagesDockWidgetVisibilityChanged(bool) (this=0x555556bd9020, visible=false) at MainWindow.cpp:3627
#86 0x0000555555db869e in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x555556bd9020, _c=QMetaObject::InvokeMetaMethod, _id=103, _a=0x7fffffffcf00) at generatedfiles/moc/moc_MainWindow.cpp:613
#87 0x00007fffed6f7525 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#88 0x00007fffef0d43c2 in QDockWidget::visibilityChanged(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#89 0x00007fffef0d8900 in QDockWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#90 0x00007fffeefb683c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#91 0x00007fffeefbe104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#92 0x00007fffed6c88a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#93 0x00007fffeeff031a in QWidgetPrivate::hideChildren(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#94 0x00007fffeeff05e4 in QWidgetPrivate::hide_helper() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#95 0x00007fffeeff4d90 in QWidget::setVisible(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#96 0x00007fffeeff08a8 in QWidgetPrivate::close_helper(QWidgetPrivate::CloseMode) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#97 0x00007fffef00f7b6 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#98 0x00007fffef012877 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#99 0x00007fffeefb683c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#100 0x00007fffeefbe104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#101 0x00007fffed6c88a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#102 0x00007fffee7f7aca in QGuiApplicationPrivate::processCloseEvent(QWindowSystemInterfacePrivate::CloseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#103 0x00007fffee7fc0e5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#104 0x00007fffee7d333b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#105 0x00007fffd598b260 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#106 0x00007fffe60a9537 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#107 0x00007fffe60a9770 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#108 0x00007fffe60a97fc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#109 0x00007fffed72185f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#110 0x00007fffed6c68da in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#111 0x00007fffed6cf984 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#112 0x00005555559b88ab in main(int, char**) (argc=1, argv=0x7fffffffdc78) at main.cpp:180
```
</details>

**Comment by adeas31** [comment]
Ported to 1.22.1. #11698
