### ISSUE TITLE
Modelica-Buildings Library (master-fmi-fmpy): FMU file is not working proprerly

### ISSUE THREAD

**Issue by deepak19015** [OpenModelica/OpenModelica#11769]
### Description

The simulation of fmu generated through omedit are not working properly. After dumping FMU in jupyter-notebook using fmpy library, it is not able simulate as well as  list out  input output variables. 
The following below listed models have same issues: 

```
Buildings.Fluid.DXSystems.Cooling.BaseClasses.Examples.UACp
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.EquipmentSchedule
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.LightsControl
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.RadiantHeatingCooling_TSurface
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.Unconditioned
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.ASHRAE2006Summer
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Spring
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Winter
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Unconditioned
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.OutputVariable.NoOutputVariable
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.OutputVariable.OneZoneOneOutputVariable
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.OutputVariable.OneZoneOutputVariable
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.OutputVariable.OneZoneTwoIdenticalOutputVariables
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.SurfaceComparison.BaseClasses.ReferenceSurfaces
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.SurfaceComparison.SurfaceComparison
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.ThermalZone.InternalGain
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.ThermalZone.OneZoneOneYear
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.ThermalZone.TwoIdenticalZones
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.ThermalZone.ZoneTemperatureInitialization
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.ZoneSurface.OneZoneControlledFloorTemperature
```
On simulating the model in jupyter-notebook using fmpy library leads to following errors/warnings:

```
1. OSError: libfmilib_shared.so: cannot open shared object file: No such file or directory
2.  Failed to load shared library 
```

### Steps to Reproduce

Load the Modelica-Buildings master fmi fmpy library (Source: https://libraries.openmodelica.org/branches/master-fmi-fmpy/Buildings_latest/Buildings_latest.html)
Right click on the model and export fmu. import the fmu in python platform and the run python code.
Simulate the model "Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.EquipmentSchedule"

### Expected Behavior

The simulation should run without any error and plot the graph according to variables present in model.

### Screenshots
![06th ticket](https://github.com/OpenModelica/OpenModelica/assets/139556265/8b73ba6a-8190-4b02-9cee-18238c27466a)

### Version and OS

-    OpenModelica Version: OpenModelica 1.23.0~dev-151-g8fef40a
-    OS: Ubuntu 22.04 focal
-    FMPy 0.3.19 
-    Python version: Python 3.10.12

       Versions of used Modelica libraries:
        Modelica 4.0.0
        Buildings master (11.0.0)

**Comment by BasilioPV** [comment]
This is related to #11604 ?

**Comment by arun3688** [comment]
@deepak19015 I tested the models in windows and the fmus are exported correctly, based on the error message i can see the it cannot find the shared library libfmilib_shared.so in your machine, MAy be the export of your FMU is corrupted, try to regenerate the fmu from command line and test it, Based on  my testing with FMPY of the following Model `Buildings.Utilities.Math.Examples.BesselY0` , I can see that the fmu fails with initialization problem 

```
(base) c:\test>python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from fmpy import *
>>> fmu = "C:/test/BesselY0.fmu"
>>> dump(fmu)

Model Info

  FMI Version        2.0
  FMI Type           Model Exchange
  Model Name         Buildings.Utilities.Math.Examples.BesselY0
  Description        Test model for besselY0 function
  Platforms          c-code, win64
  Continuous States  0
  Event Indicators   2
  Variables          7
  Generation Tool    OpenModelica Compiler v1.23.0-dev-199-g49a342bd79-cmake
  Generation Date    2023-12-28T12:14:14Z

Default Experiment

  Start Time         0.1
  Stop Time          30.0
  Tolerance          1e-06

Variables (input, output)

  Name               Causality              Start Value  Unit     Description
>>> simulate_fmu(fmu)
arun
0
BesselY0
successfull
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\fmpy\simulation.py", line 759, in simulate_fmu
    result = simulateME(model_description, fmu, start_time, stop_time, solver, step_size, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, record_events, timeout, step_finished, validate, set_stop_time)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fmpy\simulation.py", line 933, in simulateME
    fmu.exitInitializationMode()
  File "C:\ProgramData\Anaconda3\lib\site-packages\fmpy\fmi2.py", line 283, in exitInitializationMode
    return self.fmi2ExitInitializationMode(self.component)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fmpy\fmi2.py", line 215, in w
    raise FMICallException(function=fname, status=res)
fmpy.fmi1.FMICallException: fmi2ExitInitializationMode failed with status 3 (error).
>>>
```

**Comment by arun3688** [comment]
> This is related to #11604 ?

No this is not related with this issue

**Comment by deepak19015** [comment]
@arun3688 After exporting FMU through mos command line these two models are running fine.
```
Buildings.Utilities.Math.Examples.BesselY0
Buildings.Utilities.Math.Examples.ExponentialIntegralE1

```
Apart from these two model all the model has same error like this.
![Screenshot from 2024-01-04 16-57-17](https://github.com/OpenModelica/OpenModelica/assets/139556265/84b59f3b-5982-45ca-96b6-2209ea57c919)
![Screenshot from 2024-01-04 16-59-17](https://github.com/OpenModelica/OpenModelica/assets/139556265/ed98c478-4257-497b-ad46-9300713eaa8e)
Please try to simulate the following models.
```
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.EquipmentSchedule
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.LightsControl
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.RadiantHeatingCooling_TSurface
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.Unconditioned
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.ASHRAE2006Summer
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Spring
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Winter
Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Unconditioned
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.OutputVariable.NoOutputVariable
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.OutputVariable.OneZoneOneOutputVariable
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.OutputVariable.OneZoneOutputVariable
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.OutputVariable.OneZoneTwoIdenticalOutputVariables
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.SurfaceComparison.BaseClasses.ReferenceSurfaces
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.SurfaceComparison.SurfaceComparison
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.ThermalZone.InternalGain
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.ThermalZone.OneZoneOneYear
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.ThermalZone.TwoIdenticalZones
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.ThermalZone.ZoneTemperatureInitialization
Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.ZoneSurface.OneZoneControlledFloorTemperature
Buildings.Experimental.DHC.Loads.BaseClasses.Examples.CouplingSpawnZ6
Buildings.Fluid.DXSystems.Cooling.BaseClasses.Examples.UACp
```

**Comment by casella** [comment]
@mwetter, maybe I already asked you this question. As I understand, these models need some external binary code with EnergyPlus stuff. Does it make sense to run them as FMUs? If so, we should make sure that all the dependencies are actually copied into the FMU itself

**Comment by casella** [comment]
@AnHeuermann, @arun3688, do you know what is the `libfmilib_shared.so` library used for and how to get it included in the FMU?

**Comment by arun3688** [comment]
@casella the `libfmilib_shared.so` is FMI library package developed from by modelon `https://github.com/modelon-community/fmi-library, ` which is basically used for importing the FMI into other tools, And for the FMU export this will not be exported and in this case it is the FMPy library which uses FMILIB to import the fmu and  I think the users need to install in their machine or may be FMPY should automatically install it while installing FMPy,  OMSimulator uses `fmi4c` library for importing and we have plans to replace the fmilib in OpenModelica as well, This issue is related with FMPy

**Comment by casella** [comment]
@mwetter maybe I already asked you this question but I cannot find the answer - how should we manage these test cases with the OpenModelica CI - should we install the EnergyPlus runtime on the testing server (we need it for Linux!) or should we just skip them?

**Comment by mwetter** [comment]
@casella : The OpenModelica CI testing already installs the EnergyPlus runtime in `runOnceBeforeTesting`. From https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html:
```
Config:
{
 "ignoreModelPrefix": "Buildings.Utilities.IO.BCVTB.Examples",
 "library": "Buildings",
 "libraryVersion": "master",
 "libraryVersionNameForTests": "latest",
 "referenceFileExtension": "csv",
 "referenceFileNameDelimiter": "_",
 "referenceFiles": "/mnt/ReferenceFiles/Buildings/csv/master",
 "runOnceBeforeTesting": [
  [
   "$resourceLocation/src/ThermalZones/install.py",
   "--binaries-for-os-only"
  ]
 ]
```

**Comment by casella** [comment]
Indeed. It should also get installed when running the master-fmi-fmpy job, see https://libraries.openmodelica.org/branches/master-fmi-fmpy/Buildings_latest/Buildings_latest.html

The question is, why isn't that dll loaded when the time comes?

**Comment by mwetter** [comment]
The error message
https://libraries.openmodelica.org/branches/master-fmi-fmpy/Buildings_latest/files/Buildings_latest_Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SingleFamilyHouse.AirHeating.sim
comes from https://github.com/lbl-srg/modelica-buildings/blob/0847c5214b0eefd6c14aeee8856c046c2ecf3e84/Buildings/Resources/src/ThermalZones/EnergyPlus_9_6_0/C-Sources/BuildingInstantiate.c#L917

Note that this shows that the executable could not be found; it does not check whether the executable will find the dlls. This error is before any issues with dlls would be detected.

You could set in the "buildings" instance `logLevel = Buildings.ThermalZones.EnergyPlus_9_6_0.Types.LogLevels.Debug` and then the log will report which directories are searched for the executable.

My guess is that the fmi runtime environment does not have access or knowledge of `PATH` or `SPAWNPATH`.
