### ISSUE TITLE
Tabular ExternalMedia CoolProp medium models crash the NF (and OMEdit)

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12440]
Follow-up of [#12381](https://github.com/OpenModelica/OpenModelica/issues/12381#issuecomment-2116364740), check the description there.

Keeping @fedetftpolimi in the loop.

**Comment by perost** [comment]
#12443 should improve the situation a bit, by reducing the number of external functions that we evaluate. Previously we tried to evaluate all parameters, but with #12443 we don't evaluate parameter bindings that we know are impure.

This reduced the amount of external calls a lot, but it was still evaluating some problematic calls. It seems we don't really propagate pureness, so we don't know if e.g. a parameter has a binding that's a record where one of the fields has a binding that calls an impure function and so on.

Dealing with that properly is tricky, so for now I just disabled evaluation of external calls completely when dumping component bindings to JSON. I don't think there's really any good reason to be evaluating them anyway, regardless of if they're pure or not.

It doesn't completely solve the issue of calling external functions in the frontend, it'll still do it if you e.g. use an external function as an array dimension. But for any sane use of external functions this is probably good enough, and for e.g. `ExternalMedia.Examples.CO2CoolPropTabular` it reduces the number of calls from 2516 to 0.

**Comment by casella** [comment]
BTW, I'll have to mark those functions as pure (because they are) so #12443 won't be a definitive solution. I really need to figure out what is going wrong in the CoolProp solver.

@adeas31 maybe you can use a debugger while running OMEdit and show me what is contained in the pointer that causes the crash?

**Comment by adeas31** [comment]
We need a debug version of CoolProp solver if we want to see some information.

**Comment by fedetftpolimi** [comment]
Maybe you're right, but in the stack trace you could already see the function name and signature
```get_binary_file_contents(char const*)```
maybe gdb will let you put a breakpoint there and inspect the `char const*` pointer that is passed as function parameter. We don't really need to single-step into that function, just check whether that pointer is valid or not.

**Comment by adeas31** [comment]
Without debug symbols we can only see the function name not the locals. We need to compile CoolProp with debug symbols.

**Comment by casella** [comment]
@fedetftpolimi can you run CMAKE to compile that?

**Comment by fedetftpolimi** [comment]
Not for windows...

**Comment by casella** [comment]
After #12671 (which is now cherry-picked to 1.23.1 as well) when I open ExternalMedia.Examples.CO2CoolPropTabular using v1.24.0-dev-165-g8ede334557 on Windows 10, OMEdit no longer crashes, as [it did on May 17](https://github.com/OpenModelica/OpenModelica/issues/12381#issuecomment-2116364740).

However, it still does crash if I try to simulate ExternalMedia.Test.CoolProp.CO2_Tabular.TestStatesSupercritical on the same machine. It works fine on Linux.

So, the issue was **partially** addressed so far. In any case, I will eventually need to make those functions pure, so we need to figure out what goes wrong there.

**Comment by bilderbuchi** [comment]
> However, it still does crash if I try to simulate ExternalMedia.Test.CoolProp.CO2_Tabular.TestStatesSupercritical on the same machine. It works fine on Linux.

I can confirm this OMEdit crash is still happening with dc0fc08. Here's the first page or so of a gdb backtrace (that is 99 frames deep):
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff89132f33e in ?? () from C:\Repository\OM_source\build_cmake\install_cmake\bin\libstdc++-6.dll
(gdb) bt
#0  0x00007ff89132f33e in ?? () from C:\Repository\OM_source\build_cmake\install_cmake\bin\libstdc++-6.dll
#1  0x00007ff89134f508 in ?? () from C:\Repository\OM_source\build_cmake\install_cmake\bin\libstdc++-6.dll
#2  0x00007ff891350e11 in ?? () from C:\Repository\OM_source\build_cmake\install_cmake\bin\libstdc++-6.dll
#3  0x00000000703ef21f in get_binary_file_contents(char const*) ()
   from C:\Users\myuser\AppData\Roaming\.openmodelica\libraries\ExternalMedia 4.0.0\Resources\Library\win64\ExternalMediaLib.dll
#4  0x00000000705d96ee in void CoolProp::load_table<CoolProp::LogPHTable>(CoolProp::LogPHTable&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from C:\Users\myuser\AppData\Roaming\.openmodelica\libraries\ExternalMedia 4.0.0\Resources\Library\win64\ExternalMediaLib.dll
#5  0x000000007055d8b4 in CoolProp::TabularDataSet::load_tables(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<CoolProp::AbstractState>&) ()
   from C:\Users\myuser\AppData\Roaming\.openmodelica\libraries\ExternalMedia 4.0.0\Resources\Library\win64\ExternalMediaLib.dll
#6  0x000000007055f3f2 in CoolProp::TabularDataLibrary::get_set_of_tables(std::shared_ptr<CoolProp::AbstractState>&, bool&) ()
   from C:\Users\myuser\AppData\Roaming\.openmodelica\libraries\ExternalMedia 4.0.0\Resources\Library\win64\ExternalMediaLib.dll
#7  0x000000007055f899 in CoolProp::TabularBackend::load_tables() ()
   from C:\Users\myuser\AppData\Roaming\.openmodelica\libraries\ExternalMedia 4.0.0\Resources\Library\win64\ExternalMediaLib.dll
#8  0x00000000705f58d5 in CoolProp::TabularBackend::check_tables() ()
   from C:\Users\myuser\AppData\Roaming\.openmodelica\libraries\ExternalMedia 4.0.0\Resources\Library\win64\ExternalMediaLib.dll
#9  0x00000000703ec5c1 in CoolProp::AbstractState::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
   from C:\Users\myuser\AppData\Roaming\.openmodelica\libraries\ExternalMedia 4.0.0\Resources\Library\win64\ExternalMediaLib.dll
#10 0x00000000703d037c in CoolPropSolver::CoolPropSolver(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from C:\Users\myuser\AppData\Roaming\.openmodelica\libraries\ExternalMedia 4.0.0\Resources\Library\win64\ExternalMediaLib.dll
#11 0x00000000703e0f49 in SolverMap::getSolver(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from C:\Users\myuser\AppData\Roaming\.openmodelica\libraries\ExternalMedia 4.0.0\Resources\Library\win64\ExternalMediaLib.dll
#12 0x00000000703d1def in TwoPhaseMedium_getMolarMass_C_impl ()
   from C:\Users\myuser\AppData\Roaming\.openmodelica\libraries\ExternalMedia 4.0.0\Resources\Library\win64\ExternalMediaLib.dll
#13 0x00007ff8640d52e1 in ffi_call_win64 ()
    at C:/Repository/OM_source/OMCompiler/3rdParty/libffi/src/x86/win64.S:76
#14 0x00007ff8640d4f2b in ffi_call_int (cif=0x5f0f58, fn=0x703d1c90 <TwoPhaseMedium_getMolarMass_C_impl>,
    rvalue=0x3f443780, avalue=0x48a11aa0, closure=0x0)
    at C:/Repository/OM_source/OMCompiler/3rdParty/libffi/src/x86/ffiw64.c:172
#15 0x00007ff8640d4cfc in ffi_call (cif=0x5f0f58, fn=0x703d1c90 <TwoPhaseMedium_getMolarMass_C_impl>,
    rvalue=0x3f443780, avalue=0x48a11aa0)
    at C:/Repository/OM_source/OMCompiler/3rdParty/libffi/src/x86/ffiw64.c:178
#16 0x00007ff8640cd17a in FFI_callFunction (fnHandle=1, args=0x4af53963, specs=0x4af53933,
    returnType=0x7ff864414d5b <_OMC_LIT_STRUCT50+3>, outputArgs=0x5f1020)
    at C:/Repository/OM_source/OMCompiler/Compiler/runtime/ffi_omc.cpp:600
#17 0x00007ff863fc580c in omc_FFI_callFunction (threadData=0x5ffd80, _fnHandle=1, _args=0x4af53963,
    _specs=0x4af53933, _returnType=0x7ff864414d5b <_OMC_LIT_STRUCT50+3>, out_outputArgs=0x5f10c8)
    at C:/Repository/OM_source/OMCompiler/Compiler/Util/FFI.mo:11
#18 0x00007ff8632c3914 in omc_NFEvalFunction_callExternalFunction (threadData=0x5ffd80, _extName=0x404ed743,
    _fn=0x4af40803, _args=0x7ff8643f5723 <mmc_nil+3>, _extArgs=0x4af509a3, _outputRef=0x4af4f8c3,
    _extAnnotation=0x3f2e4823, _debug=0 '\000')
```
