### ISSUE TITLE
Process crashed when importing python libraries

### ISSUE THREAD

**Issue by sergiochavezlazo96** [OpenModelica/OpenModelica#12584]
### Description

Hello. I am new using OmEdit I am having problems using Python inside my Model. Currently I am running toy examples just to understand step by step towards my end goal

My problem so far is that I everytime I simulate a model that includes libraries like pandas, numpy or twinlab, the simulation crushes after one iteration.

This is my function:

`function PandasString
  input String s;
  external "C" annotation(Include = "
#include <C:/Users/sergi/AppData/Local/Programs/Python/Python312/include/Python.h>
void pyRunString(const char *str)
{
  Py_SetProgramName(L\"pyRunString\"); /* optional but recommdended */
  Py_Initialize();
  PyRun_SimpleString(str);
  Py_Finalize();
}
",
Library = "C:/Users/sergi/AppData/Local/Programs/Python/Python312/libs/python312.lib",  // Full path to the Python library
LibraryDirectory = "C:/Users/sergi/AppData/Local/Programs/Python/Python312/libs" // Path to the library files
);
end PandasString;`

This is my model:

`model PandasModel
  algorithm
    pyRunString("
try:
    import pandas as pd
    print('Pandas version',pd.__version__)
    print('Python says: simulation time', " + String(time) + ")
except Exception as e:
    print('An error occurred:', str(e))
");
end PandasModel;`

When I try to simulate (start time 0, stop time 1) I am getting:

![image](https://github.com/OpenModelica/OpenModelica/assets/147410494/18c00b54-bf4e-4dbd-9623-c0ac71eb2034)

This means that at some point it actually import pandas and read the version. 

I don't understand why it is crashing with this and numpy (both are installed), but not with other packages like os. For example, this works fine:

`model PandasModel
  algorithm
    pyRunString("
try:
    import os
    print(os.getcwd())
    print('Python says: simulation time', " + String(time) + ")
except Exception as e:
    print('An error occurred:', str(e))
");
end PandasModel;`

![image](https://github.com/OpenModelica/OpenModelica/assets/147410494/65160954-3be7-46cb-891e-081d44c3431b)

**Comment by casella** [comment]
@arun3688 any idea?

**Comment by sergiochavezlazo96** [comment]
Hello! Do you happen to have any updates on this? This is my main blocker so far to use OMEdit for my simulations. 

In a more complex example I am getting a similar error :

```
Could not find platform independent libraries <prefix> Traceback (most recent call last): File "<string>", line 1, in <module> File "C:\Python/Lib/site-packages\twinlab\__init__.py", line 10, in <module> from .client import ( File "C:\Python/Lib/site-packages\twinlab\client.py", line 9, in <module> import pandas as pd File "C:\Python/Lib/site-packages\pandas\__init__.py", line 11, in <module> __import__(_dependency) File "C:\Python/Lib/site-packages\numpy\__init__.py", line 144, in <module> from numpy.__config__ import show as show_config File "C:\Python/Lib/site-packages\numpy\__config__.py", line 4, in <module> from numpy.core._multiarray_umath import ( File "C:\Python/Lib/site-packages\numpy\core\__init__.py", line 24, in <module> from . import multiarray File "C:\Python/Lib/site-packages\numpy\core\multiarray.py", line 10, in <module> from . import overrides File "C:\Python/Lib/site-packages\numpy\core\overrides.py", line 8, in <module> from numpy.core._multiarray_umath import ( SystemError: D:\a\1\s\Objects\structseq.c:476: bad argument to internal function 
```

In this case twinlab, pandas and numpy are my non-standar libraries from python.

What confuses me (and also gives me hope) is that it actually works at the beginning for once (is even doing an API call) and then crashes :(.
