### ISSUE TITLE
Eliminate (va_)throwStreamPrint(NULL,..) as a crash source

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#13056]
leftovers from #9681: 
I'm guessing the crashing code path described [above](https://github.com/OpenModelica/OpenModelica/issues/9681#issuecomment-2393186548) (in essence, calling `throwStreamPrint(NULL,..)` or `va_throwStreamPrint(NULL,..)`) can be a problem in general. From a manual reading of the codebase without a deeper understanding, it seems to me this NULL argument should ~always lead to a segfault from within `getBestJumpBuffer` in the end, so I guess those call sites should be updated or those functions be tweaked to be more defensive.

@arun3688 says
> @bilderbuchi [...T]hat is still a problem with `throwStreamPrint(NULL)`, As you said it will lead to segfault[...] For cases related to NULL may be we should do a proper check whether the threadData !=NULL and then call the `getBestJumpBuffer` but i am not exactly sure, this can lead to errors not reported correctly or uncaught errors

_Originally posted by @bilderbuchi in https://github.com/OpenModelica/OpenModelica/issues/9681#issuecomment-2410632876_

**Comment by casella** [comment]
@arun3688 can you please take care of this? Thanks!

**Comment by casella** [comment]
@adrpo, ping! If you could take care of this, it would be nice.

**Comment by adrpo** [comment]
As far as I understand, this is not possible. When you throw you need to give someplace to jump to, you need a valid jump buffer in `threadData`, otherwise it will not work.

The runtime needs to decide where to jump when there is an error, usually in the outer loop of the solver or whatever, depending on the context where the error happens.

Sure, we could try to exit gracefully if somebody gives bad NULL value to `threadData` in `(va_)throwStreamPrint` but that is the best we can do if we don't have a jump point from where to continue.

**Comment by bilderbuchi** [comment]
> Sure, we could try to exit gracefully if somebody gives bad NULL value to `threadData` in `(va_)throwStreamPrint`

Exactly! The point is not to _crash_, but to exit gracefully.

There are many obvious occurrences of such "bad NULL values", e.g. https://github.com/search?q=repo%3AOpenModelica%2FOpenModelica+%22assertStreamPrint%28NULL%22&type=code and other patterns that end up with threadData==NULL in `(va_)throwStreamPrint`. As an additional improvement, one could eliminate these _sources_ of crash possibility, but I suspect/assume these are often there because there is no meaningful place to jump to available, so graceful handling will be necessary anyway.

**Comment by syntron** [comment]
I have no idea of the source code OMC is using but would it be possible to have a default (re)entry point which is used in the `NULL` case such that at least the error handling can be finished and a meaningfull error is printed? The messages shown in the search of @bilderbuchi would be at least an indication why there is not result data (comming from #13829)

**Comment by cbu-hw** [comment]
We just hit this problem (again) in an FMU that crashes when an internal assert fired. 
Can this be fixed by providing a meaningful default entrypoint instead of NULL, which IIUC *always* leads to a crash when hitting one of the code paths in the search result linked above?

**Comment by cbu-hw** [comment]
> We just hit this problem (again) in an FMU that crashes when an internal assert fired. Can this be fixed by providing a meaningful default entrypoint instead of NULL, which IIUC _always_ leads to a crash when hitting one of the code paths in the search result linked above?

Correction: This crash came from out of a nonlinear solve in an `rhs` call - `omc_Modelica_Math_Nonlinear_solveOneNonlinearEquation` -> `omc_Modelica_Utilities_Streams_error` -> `omc_assert_fmi`, because `threadData.mmc_jumper` was NULL. I suspected the root cause to be the same/similar, but maybe I'm wrong.

**Comment by cbu-hw** [comment]
> > We just hit this problem (again) in an FMU that crashes when an internal assert fired. Can this be fixed by providing a meaningful default entrypoint instead of NULL, which IIUC _always_ leads to a crash when hitting one of the code paths in the search result linked above?
> 
> Correction: This crash came from out of a nonlinear solve in an `rhs` call - `omc_Modelica_Math_Nonlinear_solveOneNonlinearEquation` -> `omc_Modelica_Utilities_Streams_error` -> `omc_assert_fmi`, because `threadData.mmc_jumper` was NULL. I suspected the root cause to be the same/similar, but maybe I'm wrong.

@casella could you help with resolving this issue?
In this particular case, we suspect that if there were no segfault, the solver would be able to continue with a smaller stepsize, so this crash means we can't run our FMU to completion.
We could try to get an MWE together, would that help here?

**Comment by casella** [comment]
@cbu-hw having an MWE would for sure help a lot.

**Comment by casella** [comment]
> > Sure, we could try to exit gracefully if somebody gives bad NULL value to `threadData` in `(va_)throwStreamPrint`
> 
> Exactly! The point is not to _crash_, but to exit gracefully.

What do you mean exactly by that? What would be your expected outcome in this case? Can you be more precise.

**Comment by JohannesStrechaHoerbiger** [comment]
Hi @casella, I’m working with @bilderbuchi on this topic. In the cases we observed, the FMU tries to jump to the null address when solving a nonlinear system fails, or when an assertion fails (e.g. negative temperature in the Media model). This happens in the model exchange FMUs `getDerivatives` function when the solver takes a large time-step and predicts a system state that’s outside the domain. The FMU should return `fmi2Discard`, and the proper action by the solver is to attempt a smaller time-step (see section 2.1.3 “status returned by functions” of the FMI 2.0.3 spec).

Here’s an example I cannot share, but that illustrates what’s going on: The invalid jump occurs in `omc_assert_fmi`, which tries to print the message “_The arguments u_min and u_max provided in the function call solveOneNonlinearEquation(f,u_min,u_max) do not bracket the root of the single non-linear equation 0=f(u) ..._”. `MMC_THROW_INTERNAL` wants to jump to `threadData->mmc_jumper`, which is not set.

<img width="945" height="149" alt="Image" src="https://github.com/user-attachments/assets/6df5d667-1772-4483-94cc-63158ece2ed0" />

The error occurred when calling `getDerivatives`. The call stack in the FMU is:

    omc_assert_fmi(threadData_s * threadData, _FILE_INFO info, volatile char * msg) 
    omc_Modelica_Utilities_Streams_error(threadData_s * threadData, void * _string)
    omc_Modelica_Math_Nonlinear_solveOneNonlinearEquation(threadData_s * threadData, void * _f, double _u_min, double _u_max, double _tolerance) demoModel_eqFunction_579(DATA * data, threadData_s * threadData)
    functionODE_system0(DATA * data, threadData_s * threadData)

Here’s an MWE that I can share. It has a volume using the media model and the crash will be triggered by setting a negative temperature before getting the derivatives. It shows the same behavior as the real use-case above, although the stack trace is slightly different.

    model MmcJumperRepro
      Modelica.Fluid.Machines.SweptVolume sweptVolume(redeclare package Medium = Modelica.Media.IdealGases.SingleGases.N2, pistonCrossArea = 1, clearance = 0.1, p_start = 1e5, T_start = 298.15);
      Modelica.Mechanics.Translational.Sources.Position position;
      Modelica.Blocks.Sources.Ramp ramp(height = 0.1, duration = 1);
    equation
      connect(position.flange, sweptVolume.flange);
      connect(ramp.y, position.s_ref);
    end MmcJumperRepro;

Using OpenModelica 1.26.3 (Windows) to generate an FMU and issuing the following calls (pyfmi) will crash the process. The first (functionODE_system0) and last function (omc_assert_fmi) in the call stack of this MWE are the same as in the above call stack, but the functions in between are different, of course.

    # Load the FMU, instantiate a model, and go through the normal startup sequence
    fmu = pyfmi.load_fmu(/path/to/MmcJumperRepro.fmu)
    fmu.instantiate()
    fmu.setup_experiment()
    fmu.enter_initialization_mode()
    fmu.exit_initialization_mode()
    fmu.event_update()
    fmu.enter_continuous_time_mode()

    # set an illegal input. In a real use-case this would be a solver mispredicting a system state
    fmu.set('sweptVolume.medium.T', -1)
    # This crashes the process because mmc_jumper is null.
    fmu.get_derivatives()

**Comment by adrpo** [comment]
PR #15681 should fix the crash
```
(base) adrpo33@win06527:~/testing/13056$ python3 run-fmu.py 
Traceback (most recent call last):
  File "/home/adrpo33/testing/13056/run-fmu.py", line 15, in <module>
    fmu.get_derivatives()
    ~~~~~~~~~~~~~~~~~~~^^
  File "src/pyfmi/fmi2.pyx", line 4717, in pyfmi.fmi2.FMUModelME2.get_derivatives
  File "src/pyfmi/fmi2.pyx", line 4738, in pyfmi.fmi2.FMUModelME2.get_derivatives
pyfmi.exceptions.FMUException: Failed to get the derivative values at time: 0.000000E+00.
```

I'll see about adding this test for it using OMSimulator as we don't have pyfmi during testing.

**Comment by adrpo** [comment]
I think we return fmi2Error if we get an assertion. I guess we would need to find the cause of the assertion and return fmi2Discard instead if it failed in some system solving. I'll check if is possible to do that.

**Comment by cbu-hw** [comment]
Thanks for the fix! We'll test this asap.

However, I think closing this issue is a bit premature, as that fix only fixed _one_ occurrence of the problem, but not all/most of the (regularly appearing) crash sources, so I think this should be reopened.

**Comment by adrpo** [comment]
I did not want to close the issue, github does automatically if you have "Fix" in the commit text :)

**Comment by cbu-hw** [comment]
ah yes, that is normally useful, but sometimes not so much. :-)

**Comment by JohannesStrechaHoerbiger** [comment]
@adrpo I can confirm that PR #15681 fixes both cases where I observed the crash (explicitly setting an input outside the domain, and a failing bracketing). Thank you!

Should I create a separate issue for fmi2Error vs fmi2Discard?

**Comment by adrpo** [comment]
Please do.

**Comment by cbu-hw** [comment]
> Please do.

Done, see #15717

**Comment by casella** [comment]
I'm going to close this, since we have a follow-up issue #15717.

**Comment by cbu-hw** [comment]
> I'm going to close this, since we have a follow-up issue [#15717](https://github.com/OpenModelica/OpenModelica/issues/15717).

I'm sorry, but I think this is premature. The recent PR 
>  only fixed one occurrence of the problem, but not all/most of the (regularly appearing) crash sources, so I think this should be reopened.

The follow-up #15717 is for a separate issue/enhancement.

AFAICT, the root cause, crashes because of calling `[va_]throwStreamPrint(NULL)`, remains unfixed in general, and issues that are suspected to be connected/maybe-caused by this remain open: #9362, #13551, #13829, #15431.

**Comment by adrpo** [comment]
I will leave this open until I have time to look at all the other tickets.

**Comment by cbu-hw** [comment]
Cross-referencing #16062 by @jschueller, which AFAICT implements a fix for a similar problem for FMUs...maybe an equivalent fix could also be applicable here?
