### ISSUE TITLE
getErrorString raises pyparsing.ParseException after calling buildModel in the python interface

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5230]

**Comment by MatthiasBSchaefer** [comment]
I detected again this behaviour:

import OMPython
interface=OMPython.OMCSessionZMQ()
interface.sendExpression('setDebugFlags("backenddaeinfo")')
interface.sendExpression('buildModel(Modelica.Blocks.Examples.PID_Controller)')
interface.sendExpression('getErrorString()')

The last command results in
>>> Result of 'getErrorString()' cannot be parsed!
'""\n'

I am using OpenModelica 1.26.3 and OMPython-4.0.1
The building of the model is successful. Doing the same on the OpenModelica Compiler CLI (started from OMEdit) the same commands are working well.

**Comment by casella** [comment]
@arun3688 can you please check this? It is high priority for the testing of MSL by MAP-Lib. Thanks!

**Comment by arun3688** [comment]
@MatthiasBSchaefer this is not an error and it is indeed an warning, see the code block below

```
 if expr == "getErrorString()":
     # no error handling if 'getErrorString()' is called
     if parsed:
         logger.warning("Result of 'getErrorString()' cannot be parsed!")
     return result
```
and if you use the logging in your code something like below, you can see the msg as warning 

```
>>> import logging
>>> logging.basicConfig(level=logging.WARNING)
>>> from OMPython import OMCSessionZMQ
>>> omc = OMCSessionZMQ()
>>> omc.sendExpression("getErrorString()")
WARNING:OMPython.OMCSession:Result of 'getErrorString()' cannot be parsed!
'""\n'
```

There are lot of changes done with the OMPython 4.0 and most of the work is done by @syntron, So right now you don't need to use `getErrorString()`, The errors are reported automatically,  An example would be 

```
>>> from OMPython import OMCSessionZMQ
>>> omc = OMCSessionZMQ()
>>> omc.sendExpression("buildModel(a)")

ERROR:OMPython.OMCSession:[OMC log for 'sendExpression(expr=buildModel(a), parsed=True)']: [scripting:error:184] Failed to load package a (default) using MODELICAPATH C:/Users/arupa54/AppData/Roaming/.openmodelica/libraries/.
ERROR:OMPython.OMCSession:[OMC log for 'sendExpression(expr=buildModel(a), parsed=True)']: [translation:error:3] Class a not found in scope <top>.
Traceback (most recent call last):
  File "<python-input-5>", line 1, in <module>
    omc.sendExpression("buildModel(a)")
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\OPENMODELICAGIT\OpenModelica\OMPython\OMPython\OMCSession.py", line 1406, in sendExpression
    return self.omc_process.sendExpression(expr=command, parsed=parsed)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\OPENMODELICAGIT\OpenModelica\OMPython\OMPython\OMCSession.py", line 1206, in sendExpression
    raise OMCSessionException(f"OMC error occurred for 'sendExpression(expr={expr}, parsed={parsed}):\n"
                              f"{msg_long_str}")
OMPython.OMCSession.OMCSessionException: OMC error occurred for 'sendExpression(expr=buildModel(a), parsed=True):
00: [scripting:error:184] [:false:0:0:0:0] Failed to load package a (default) using MODELICAPATH C:/Users/arupa54/AppData/Roaming/.openmodelica/libraries/.
01: [translation:error:3] [:false:0:0:0:0] Class a not found in scope <top>.
```

**Comment by MatthiasBSchaefer** [comment]
@arun3688 Thank you for your response !

With OMPython 3.6.0 , the getErrorString() command in my script (see my first comment) gives the whole output of building the model with setDebugFlags("backenddaeinfo"), not only the errors appearing.

With OMPython 4.0.1 the output of getErrorString() remains empty (or only reports errors anymore ?) 

In case only errors are reported by getErrorString in the newer version: Is there an other way to receive the daebackendinfo via OMPython ?

Thank you !

**Comment by arun3688** [comment]
@MatthiasBSchaefer  yes with the new OMPython 4.0.1 the output remains empty. And to get the information or notifcation via the debug flags for example in your case `daebackendinfo ` we need to use logging.INFO to get all the information from the compiler, so your script should look like below

```
import logging
logging.basicConfig(level=logging.INFO)

from OMPython import OMCSessionZMQ
interface=OMCSessionZMQ()
interface.sendExpression('setDebugFlags("backenddaeinfo")')
interface.sendExpression('buildModel(Modelica.Blocks.Examples.PID_Controller)') 
```
### Output

```
INFO:OMPython.OMCSession:Local OMC Server is up and running at ZMQ port tcp://127.0.0.1:59763 pid=23908
INFO:OMPython.OMCSession:[OMC log for 'sendExpression(buildModel(Modelica.Blocks.Examples.PID_Controller), True)']: [scripting:notification:223] Automatically loaded package Complex 4.0.0 due to uses annotation from Modelica.
INFO:OMPython.OMCSession:[OMC log for 'sendExpression(buildModel(Modelica.Blocks.Examples.PID_Controller), True)']: [scripting:notification:223] Automatically loaded package ModelicaServices 4.0.0 due to uses annotation from Modelica.
INFO:OMPython.OMCSession:[OMC log for 'sendExpression(buildModel(Modelica.Blocks.Examples.PID_Controller), True)']: [scripting:notification:391] Automatically loaded package Modelica default due to usage.
INFO:OMPython.OMCSession:[OMC log for 'sendExpression(buildModel(Modelica.Blocks.Examples.PID_Controller), True)']: [symbolic:notification:258] Model statistics after passing the front-end and creating the data structures used by the back-end:
 * Number of equations: 89
 * Number of variables: 89
INFO:OMPython.OMCSession:[OMC log for 'sendExpression(buildModel(Modelica.Blocks.Examples.PID_Controller), True)']: [symbolic:notification:259] Model statistics after passing the back-end for initialization:
 * Number of independent subsystems: 9
 * Number of states: 0 ('-d=stateselection' for list of states)
 * Number of discrete variables: 3 ('-d=discreteinfo' for list of discrete vars)
 * Number of discrete states: 0 ('-d=discreteinfo' for list of discrete states)
 * Number of clocked states: 0 ('-d=discreteinfo' for list of clocked states)
 * Top-level inputs: 0
INFO:OMPython.OMCSession:[OMC log for 'sendExpression(buildModel(Modelica.Blocks.Examples.PID_Controller), True)']: [symbolic:notification:261] Strong component statistics for initialization (51):
 * Single equations (assignments): 50
 * Array equations: 0
 * Algorithm blocks: 0
 * Record equations: 0
 * When equations: 0
 * If-equations: 0
 * Equation systems (not torn): 1
 * Torn equation systems: 0
 * Mixed (continuous/discrete) equation systems: 0
INFO:OMPython.OMCSession:[OMC log for 'sendExpression(buildModel(Modelica.Blocks.Examples.PID_Controller), True)']: [symbolic:notification:262] Equation system details (not torn):
 * Constant Jacobian (size): 0 systems
 * Linear Jacobian (size,density): 0 systems
 * Non-linear Jacobian (size): 1 system
   {1}
 * Without analytic Jacobian (size): 0 systems
INFO:OMPython.OMCSession:[OMC log for 'sendExpression(buildModel(Modelica.Blocks.Examples.PID_Controller), True)']: [symbolic:notification:259] Model statistics after passing the back-end for simulation:
 * Number of independent subsystems: 5
 * Number of states: 6 ('-d=stateselection' for list of states)
 * Number of discrete variables: 1 ('-d=discreteinfo' for list of discrete vars)
 * Number of discrete states: 0 ('-d=discreteinfo' for list of discrete states)
 * Number of clocked states: 0 ('-d=discreteinfo' for list of clocked states)
 * Top-level inputs: 0
INFO:OMPython.OMCSession:[OMC log for 'sendExpression(buildModel(Modelica.Blocks.Examples.PID_Controller), True)']: [symbolic:notification:261] Strong component statistics for simulation (32):
 * Single equations (assignments): 32
 * Array equations: 0
 * Algorithm blocks: 0
 * Record equations: 0
 * When equations: 0
 * If-equations: 0
 * Equation systems (not torn): 0
 * Torn equation systems: 0
 * Mixed (continuous/discrete) equation systems: 0
```

**Comment by casella** [comment]
@arun3688 do we have documentation of the changes between 3.6.0 and 4.0.x? Not getting anything out of getErrorString() is not a trivial change.

**Comment by casella** [comment]
@MatthiasBSchaefer please close when everything is resolved for you.

**Comment by MatthiasBSchaefer** [comment]
@arun3688 Unfortunately it seems not to be possible to get the output in a processible way (for parsing) anymore.
Any of my attempts to redirect logger-output /stdout into file /python variable fails.

**Comment by arun3688** [comment]
@MatthiasBSchaefer if you aim is to redirect the logger-output to a file then the following script should work

```
import logging
logging.basicConfig(
    level=logging.INFO,
    handlers=[
        logging.FileHandler("ompython.log", mode="w"),
        logging.StreamHandler()
    ],
    format="%(asctime)s %(levelname)s %(message)s"
)
from OMPython import OMCSessionZMQ
interface=OMCSessionZMQ()
interface.sendExpression('setDebugFlags("backenddaeinfo")')
interface.sendExpression('buildModel(Modelica.Blocks.Examples.PID_Controller)')
```
Since most of the new devellopment is done by @syntron can you please comment on you want to disable `getErrorString()` parsing

**Comment by syntron** [comment]
@MatthiasBSchaefer Please check the definition of `sendExpression()` - after each command, OMC:`getMessagesStringInternal()` is called and the returned data is send to the log using different levels based on the level in the original OMC message. For *all* output use logging.DEBUG.

If something is missing please report. It would help, if you could provide the output of the logger as well as the expected output.
