### ISSUE TITLE
FMU does not update values properly

### ISSUE THREAD

**Issue by lenaRB** [OpenModelica/OpenModelica#8241]
### Description

The FMU exported with OM is not updating the values properly. Since terminate() equations do not work with FMIs I read the value of the variable tank.failure_code and stop the simulation when it hits a certain value. Only now it is not updated properly so the simulation crashed, works just fine with the FMU I exported a couple of months ago with OM.

### Steps to Reproduce

export the HeatedTank_with_failures.system model as an FMU (attached)
rename to HeatedTank.fmu (example attached)
run the script MCScript (attached), the model crashes when it should stop because the value is not properly updated for tank.failure_code

### Expected Behavior

the model to stop simulation when the failure occurs and the value changes from 0 to 1/2/3

### Version and OS

 - OpenModelica Version: OMCompiler v1.19.0-dev.353+g257a47e656
 - OS: Mac 11.6, same problem on Linux
 - Versions of used Modelica libraries if applicable : N/A

### Additional Context

[Archive.zip](https://github.com/OpenModelica/OpenModelica/files/7617716/Archive.zip)

**Comment by adrpo** [comment]
gdb trace seems to point to some longjmp with an empty buffer, @AnHeuermann did you do something recently with this?

```
(gdb) bt
#0  __libc_siglongjmp (env=0x0, val=1) at ../setjmp/longjmp.c:32
#1  0x00007ffff7dacf3f in longjmp_compat (env=<optimized out>, val=<optimized out>) at ../sysdeps/x86/nptl/pt-longjmp.c:62
#2  0x00007ffff47aad92 in omc_terminate_function () from /mnt/c/home/adrpo33/dev/OMTesting/LenaFMU/mc-ce44ymli/temp/0001_system/binaries/linux64/HeatedTank.so
#3  0x00007ffff47929ce in HeatedTank_eqFunction_115 () from /mnt/c/home/adrpo33/dev/OMTesting/LenaFMU/mc-ce44ymli/temp/0001_system/binaries/linux64/HeatedTank.so
#4  0x00007ffff4793d37 in HeatedTank_functionDAE () from /mnt/c/home/adrpo33/dev/OMTesting/LenaFMU/mc-ce44ymli/temp/0001_system/binaries/linux64/HeatedTank.so
#5  0x00007ffff479eaad in fmi2EventUpdate () from /mnt/c/home/adrpo33/dev/OMTesting/LenaFMU/mc-ce44ymli/temp/0001_system/binaries/linux64/HeatedTank.so
#6  0x00007ffff47a4fea in fmi2DoStep () from /mnt/c/home/adrpo33/dev/OMTesting/LenaFMU/mc-ce44ymli/temp/0001_system/binaries/linux64/HeatedTank.so
#7  0x00007ffff3817caf in oms::ComponentFMUCS::stepUntil(double) () from /home/adrpo33/.local/lib/python3.8/site-packages/OMSimulator/libOMSimulator.so
#8  0x00007ffff38d41a0 in oms::SystemWC::doStep() () from /home/adrpo33/.local/lib/python3.8/site-packages/OMSimulator/libOMSimulator.so
#9  0x00007ffff38671cd in oms::Model::doStep() () from /home/adrpo33/.local/lib/python3.8/site-packages/OMSimulator/libOMSimulator.so
#10 0x00007ffff388bdf1 in oms_doStep () from /home/adrpo33/.local/lib/python3.8/site-packages/OMSimulator/libOMSimulator.so
#11 0x00007ffff7786ff5 in ?? () from /usr/lib/x86_64-linux-gnu/libffi.so.7
#12 0x00007ffff778640a in ?? () from /usr/lib/x86_64-linux-gnu/libffi.so.7
#13 0x00007ffff6e71306 in _ctypes_callproc () from /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#14 0x00007ffff6e71ae7 in ?? () from /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#15 0x00000000005f698e in _PyObject_MakeTpCall ()
#16 0x000000000057148b in _PyEval_EvalFrameDefault ()
#17 0x00000000005f6166 in _PyFunction_Vectorcall ()
#18 0x000000000056bf09 in _PyEval_EvalFrameDefault ()
#19 0x00000000005f6166 in _PyFunction_Vectorcall ()
#20 0x000000000056bf09 in _PyEval_EvalFrameDefault ()
#21 0x000000000056a0ba in _PyEval_EvalCodeWithName ()
#22 0x000000000068d5b7 in PyEval_EvalCode ()
#23 0x000000000067cd01 in ?? ()
#24 0x000000000067cd7f in ?? ()
#25 0x000000000067ce21 in ?? ()
#26 0x000000000067ef47 in PyRun_SimpleFileExFlags ()
#27 0x00000000006b7242 in Py_RunMain ()
#28 0x00000000006b75cd in Py_BytesMain ()
#29 0x00007ffff7de30b3 in __libc_start_main (main=0x4eec50 <main>, argc=2, argv=0x7fffffffdf58, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffdf48) at ../csu/libc-start.c:308
#30 0x00000000005fb18e in _start ()
(gdb) quit
```
script to generate the FMU is attached [8241-files.zip](https://github.com/OpenModelica/OpenModelica/files/7710802/8241-files.zip)

**Comment by AnHeuermann** [comment]
I don't think so. I did something with asserts in #8118, maybe that is a problem for some FMUs?
