### ISSUE TITLE
Generated FMU points to undefined symbol "hybrj_" or "enorm_"

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#8548]
### Description
When generating an FMU from a simple heatflow system the generated model is pointing to an undefined symbol and hence can not be run.

### Steps to Reproduce

1. Open `Modelica.Thermal.FluidHeatFlow.Examples.SimpleCooling` in OMEdit and export as FMU (I had the settings blackbox and Euler solver)

Running the resultant FMU in FMPy will result in an error message: 

```
Failed to load shared library /tmp/tmp33drwxp6/binaries/linux64
/Modelica_Thermal_FluidHeatFlow_Examples_SimpleCooling.so. /tmp/tmp33drwxp6/binaries/linux64
/Modelica_Thermal_FluidHeatFlow_Examples_SimpleCooling.so: undefined symbol: hybrj_
```

In a different model I got a similar undefined symbol `enorm_`

### Expected Behavior

There should be no error message. 

### Version and OS

 - OpenModelica Version: OpenModelica 1.19.0~dev-573-g07173a7
 - OS: Ubuntu Linux 20.04
 - Versions of used Modelica libraries if applicable MSL 4.0.0

**Comment by arun3688** [comment]
@dietmarw I build the fmu with same settings in windows and tested with OMSimulator it works for me

```
# OMSimulator Modelica.Thermal.FluidHeatFlow.Examples.SimpleCooling.fmu
info:    maximum step size for 'model.root': 0.001000
info:    Result file: model_res.mat (bufferSize=10)
info:    Final Statistics for 'model.root':
         NumSteps = 1001 NumRhsEvals  = 1002 NumLinSolvSetups = 52
         NumNonlinSolvIters = 1001 NumNonlinSolvConvFails = 0 NumErrTestFails = 0
```

**Comment by AnHeuermann** [comment]
`hybrj_` is from CMinpack and used for the default non-linear solver the runtime uses.

For source-code FMUs the sources were not added to the FMU. I fixed that in https://github.com/OpenModelica/OpenModelica/commit/ed1e04280491a3d5f33a5c71b08f884cc26381be and improved it in https://github.com/OpenModelica/OpenModelica/commit/eb0ed2668e8ad5d14df27fbb1c66d1585beb18c3.

**Comment by sjoelund** [comment]
Does the XML-file contain the correct files after this update? (For the source-code FMU importers out there relying on it)

**Comment by AnHeuermann** [comment]
No, the modelDescription.xml is missing these CMinpack source file information. See https://github.com/OpenModelica/OpenModelica/issues/8524

**Comment by dietmarw** [comment]
@arun3688 Unfortunately I can not test it with OMSimulator because of #8163. But it is not really relevant since it need to be able to run in an independent tool like FMPy where there is no openmodelica installed.

**Comment by arun3688** [comment]
@dietmarw you can install OMSimulator using `pip3 install OMSimulator`, but as you said it should work in `FMPY` as well, I guess the issue is related with linux, because the windows generated fmu worked in FMPY as well for me.

```
>>> from fmpy import *
>>> fmu = "Modelica.Thermal.FluidHeatFlow.Examples.SimpleCooling.fmu"
>>> dump(fmu)

Model Info

  FMI Version       2.0
  FMI Type          Model Exchange, Co-Simulation
  Model Name        Modelica.Thermal.FluidHeatFlow.Examples.SimpleCooling
  Description       Simple cooling circuit
  Platforms         win64
  Continuous States 2
  Event Indicators  0
  Variables         7
  Generation Tool   OpenModelica Compiler OpenModelica v1.19.0-dev-588-gd13c544b4a (64-bit)
  Generation Date   2022-02-15T13:38:03Z

Default Experiment

  Stop Time         1
  Tolerance         1e-06

Variables (input, output)

Name                Causality              Start Value  Unit     Description
dTCoolant           output                              K        Coolant's temperature increase
dTSource            output                              K        Source over Ambient
dTtoPipe            output                              K        Source over Coolant
>>> result = simulate_fmu(fmu)
>>> print(result)
```

**Comment by AnHeuermann** [comment]
I can't reproduce the error on Linux 20.04 with omc v1.19.0-dev-587-g8d0b1ce875 (but I'm on a CMake build which could be slightly different to the one installed via `apt`).

@dietmarw You don't have https://github.com/OpenModelica/OpenModelica/commit/eb0ed2668e8ad5d14df27fbb1c66d1585beb18c3. Could you try again with todays master?


This is the script I'm running:
```
loadModel(Modelica, {"4.0.0"}); getErrorString();
setCommandLineOptions("--fmiFilter=blackBox --fmiFlags=s:euler"); getErrorString();
buildModelFMU(Modelica.Thermal.FluidHeatFlow.Examples.SimpleCooling, version="2.0", fmuType="cs"); getErrorString();
```

```
>>> from fmpy import *
>>> fmu = "Modelica.Thermal.FluidHeatFlow.Examples.SimpleCooling.fmu"
>>> result = simulate_fmu(fmu)
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.000000. That might raise performance issues, for more information use -lv LOG_LS.
```

**Comment by dietmarw** [comment]
Yes looks like it is an OS issue but probably on the OM side since the same model exported by Dymola works fine.
OMC export:
```
>>> from fmpy import *
>>> fmu = "Modelica.Thermal.FluidHeatFlow.Examples.SimpleCooling.fmu"
>>> dump(fmu)

Model Info

  FMI Version        2.0
  FMI Type           Model Exchange, Co-Simulation
  Model Name         Modelica.Thermal.FluidHeatFlow.Examples.SimpleCooling
  Description        Simple cooling circuit
  Platforms          linux64
  Continuous States  2
  Event Indicators   0
  Variables          7
  Generation Tool    OpenModelica Compiler OpenModelica 1.19.0~dev-573-g07173a7
  Generation Date    2022-02-15T10:58:49Z

Default Experiment

  Stop Time          1.0
  Tolerance          1e-06

Variables (input, output)

  Name               Causality              Start Value  Unit     Description
  dTCoolant          output                              K        Coolant's temperature increase
  dTSource           output                              K        Source over Ambient
  dTtoPipe           output                              K        Source over Coolant
>>> result = simulate_fmu(fmu)
Traceback (most recent call last):
  File "/home/dietmarw/.venv/fmi/lib/python3.8/site-packages/fmpy/fmi1.py", line 160, in __init__
    self.dll = cdll.LoadLibrary(libraryPath)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/tmpjsykq790/binaries/linux64/Modelica_Thermal_FluidHeatFlow_Examples_SimpleCooling.so: undefined symbol: hybrj_

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dietmarw/.venv/fmi/lib/python3.8/site-packages/fmpy/simulation.py", line 705, in simulate_fmu
    fmu = instantiate_fmu(unzipdir, model_description, fmi_type, visible, debug_logging, logger, fmi_call_logger, None, early_return_allowed, use_event_mode)
  File "/home/dietmarw/.venv/fmi/lib/python3.8/site-packages/fmpy/simulation.py", line 777, in instantiate_fmu
    fmu = FMU2Slave(**fmu_args)
  File "/home/dietmarw/.venv/fmi/lib/python3.8/site-packages/fmpy/fmi2.py", line 520, in __init__
    super(FMU2Slave, self).__init__(**kwargs)
  File "/home/dietmarw/.venv/fmi/lib/python3.8/site-packages/fmpy/fmi2.py", line 85, in __init__
    super(_FMU2, self).__init__(**kwargs)
  File "/home/dietmarw/.venv/fmi/lib/python3.8/site-packages/fmpy/fmi1.py", line 162, in __init__
    raise Exception("Failed to load shared library %s. %s" % (libraryPath, e))
Exception: Failed to load shared library /tmp/tmpjsykq790/binaries/linux64/Modelica_Thermal_FluidHeatFlow_Examples_SimpleCooling.so. /tmp/tmpjsykq790/binaries/linux64/Modelica_Thermal_FluidHeatFlow_Examples_SimpleCooling.so: undefined symbol: hybrj_
```
Dymola export:
```
>>> from fmpy import *
>>> fmu = "Modelica_Thermal_FluidHeatFlow_Examples_SimpleCooling.fmu"
>>> dump(fmu)

Model Info

  FMI Version        2.0
  FMI Type           Model Exchange, Co-Simulation
  Model Name         Modelica.Thermal.FluidHeatFlow.Examples.SimpleCooling
  Description        Simple cooling circuit
  Platforms          linux64
  Continuous States  2
  Event Indicators   0
  Variables          7
  Generation Tool    Dymola Version 2022x (64-bit), 2021-10-08
  Generation Date    2022-02-15T12:55:16Z

Default Experiment

  Stop Time          1.0
  Tolerance          0.0001

Variables (input, output)

  Name               Causality              Start Value  Unit     Description
  dTSource           output                              K        Source over Ambient
  dTtoPipe           output                              K        Source over Coolant
  dTCoolant          output                              K        Coolant's temperature increase
>>> result = simulate_fmu(fmu)
>>> print(result)
```

**Comment by sjoelund** [comment]
> Yes looks like it is an OS issue but probably on the OM side since the same model exported by Dymola works fine.

Your OMC version is from February 10. Andreas fixed something February 11.

**Comment by dietmarw** [comment]
OK that was the problem. Everything is fine with the latest nightly: 
`1.19.0~dev-586-gbf2fb17`
Sorry about the noise.
