### ISSUE TITLE
Impossible to run a very simple .ssp case based on Dymola FMUs

### ISSUE THREAD

**Issue by jph-tavella** [OpenModelica/OpenModelica#8795]
### Description

It is impossible to run a very simple .ssp case based on Dymola FMUs. The same case only involving OM FMUs is perfectly runnable with correct results.

### Steps to Reproduce

Easy to reproduce with the attached .ssp file.

### Expected Behavior

Same results as for the pure OM FMUs case.

### Screenshots
![image](https://user-images.githubusercontent.com/32952030/161217942-e9709cf8-f14c-46cf-a757-d7fc12dcee2e.png)

![image](https://user-images.githubusercontent.com/32952030/161217868-cd2e57a0-3e3a-4402-911a-dccad1c3d18d.png)

### Version and OS
 - OpenModelica Version: OpenModelica v1.19.0-dev-637-g5d2381ceaf (64-bit) connected to OMSimulator v2.1.1.post147-gc906bb0-mingw
 - Windows 10, 64 bit
[tankBarrelDymola.zip](https://github.com/OpenModelica/OpenModelica/files/8395693/tankBarrelDymola.zip)

**Comment by arun3688** [comment]
@jph-tavella I could able to reproduce the issue, from the initial debugging it seems the dymola fmus have problems with exporting the results in `.csv` format, I set the result file to `.mat ` and it worked from command Line

```
OMSimulator tankBarrelDymola.ssp --resultFile="tanktest.mat"
info:    Result file: tanktest.mat (bufferSize=1)
```
Can you change the result file to `".mat" `and see if this works

**Comment by arun3688** [comment]
@jph-tavella I debugged the ssp little more and found that the issue is not related to `Dymola` fmus or `OpenModelica` fmus, it is rather related to path of the `csv file and permission error`, in your Dymola generated ssp file, if you change the path of the csv file from` C:\tankBarrelDymola_res.csv` to `tankBarrelDymola_res.csv` this should work, it is a bug and we will fix it soon

**Comment by jph-tavella** [comment]
@arun3688 You are partly right.
When I try the pure OM FMUs case it is successful with this result file C:\Temp\tankBarrel_res.csv and it crashes with C:\tankBarrel_res.csv (permission error).
But with the pure Dymola FMUs case, it always fails, whatever the fullname result file used. And also with .mat extension.
Using the name C:\Temp\tankBarrel_res.csv, the error messages are clearer and it appears there is an issue on the terminaison of tank2 FMU as stated here (seems to be a square root of a negative real, but strange as the Modelica codes of FMUs are identical as with the case with pure OM FMUs):

python C:/OM1.19.0-dev/share/OMSimulator/scripts/OMSimulatorServer.py --model=C:/Users/a37619/AppData/Local/Temp/OpenModelica/OMEdit//tankBarrelDymola.ssp --endpoint-pub=tcp://127.0.0.1:52381 --logLevel=2 --option "--suppressPath=true" "--wallTime=true" "--directionalDerivatives=true" "--emitEvents=false"
warning: debug logging is not available
server:  OMS Server 2.1.1.post147
server:  ZMQ 4.2.3
server:  PUB socket connected to tcp://127.0.0.1:52381
info:    Result file: C:\Temp\tankBarrel_res.csv (bufferSize=10)
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.13657138338892
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-1.46483)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.13657138338892
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.150599)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 17.19254352721317
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-1.84574)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 17.19254352721317
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.89441)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 19.76487465888643
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.881713)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 19.76487465888643
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-2.8976)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.30636252349034
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.121521)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 15.72994383425766
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.00641771)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 15.72994383425766
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.00320848)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.30636252349035
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.0720123)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 15.76597000233471
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.00356273)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.13774961268154
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.00266291)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.0652265408012
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.000400117)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.18183410309449
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.000109676)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.18183410309449
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.000877108)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.11406587021454
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-4.30633e-05)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.09712381199455
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.000131453)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.09288829743955
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.000138894)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.0918294188008
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.000139839)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.09156469914112
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.000140018)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.0914985192262
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.000140059)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.09148197424746
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.000140069)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.09147783800278
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.000140071)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): Error: The following error was detected at time: 16.09147680394161
error:   [fmi2logger] tank2 (): 
         Model error - sqrt (19.62*_StatesForOutputs.level) = sqrt (-0.000140072)
error:   [fmi2logger] tank2 (): fmi2GetDerivatives: dsblock_ failed, QiErr = 1
error:   [fmi2logger] tank2 (): SUNDIALS_ERROR: CVode() failed with flag = CV_REPTD_RHSFUNC_ERR
error:   [fmi2logger] tank2 (): fmi2DoStep: integration_step failed
warning: tank2 (): CVODE: CVode failed with CV_REPTD_RHSFUNC_ERR:
          At t = 16.0915 repeated recoverable right-hand side function errors.
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2DoStep: model is terminated
warning: tank2 (): fmi2Terminate: already terminated, ignoring call
error:   [terminate] Termination of system "tank2" failed
error:   [terminate] Termination of system "tankBarrelDymola.Root" failed
Traceback (most recent call last):
  File "C:/OM1.19.0-dev/share/OMSimulator/scripts/OMSimulatorServer.py", line 195, in <module>
    _main()
  File "C:/OM1.19.0-dev/share/OMSimulator/scripts/OMSimulatorServer.py", line 192, in _main
    server.run()
  File "C:/OM1.19.0-dev/share/OMSimulator/scripts/OMSimulatorServer.py", line 167, in run
    self._model.terminate()
  File "C:\OM1.19.0-dev\lib\OMSimulator\Model.py", line 52, in terminate
    raise Exception('error {}'.format(Types.Status(status)))
Exception: error Status.ERROR
Process crashedProcess crashed
Simulation process failed. Exited with code 0xffffffffc0000005.

**Comment by arun3688** [comment]
@jph-tavella the issue should be fixed, please test with the latest nightly builds
