### ISSUE TITLE
OMC cannot initialize the Nordic44 models from OpenIPSL

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9183]
OMC currently segfaults when solving the initial equations of [OpenIPSL.Examples.DAEMode.N44_Base_Case_Systems.Nordic44_Base_Case_StateEvents](https://libraries.openmodelica.org/branches/master/OpenIPSL/files/OpenIPSL_OpenIPSL.Examples.DAEMode.N44_Base_Case_Systems.Nordic44_Base_Case_StateEvents.sim) on Linux. 

With previous versions (e.g. 1.18.0), the same model [timed out](https://libraries.openmodelica.org/branches/v1.18/OpenIPSL/files/OpenIPSL_OpenIPSL.Examples.DAEMode.N44_Base_Case_Systems.Nordic44_Base_Case_StateEvents.sim), probably because the dense solver was still used.

Apparently, there is still some memory management issue with Kinsol, please double check that.

Keeping @marcelofcastro and @GiuseppeLaera in the loop.

**Comment by AnHeuermann** [comment]
Here's a stack trace by gbd

```
Thread 1 "OpenIPSL.Exampl" received signal SIGSEGV, Segmentation fault.
0x00007ffff789ca46 in nlsSparseJac (vecX=0xc8f2a20, vecFX=0xc8f8c20, Jac=0xc9941e0, userData=0xc8f29f0, tmp1=0xc9933e0, tmp2=0xc9933c0)
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/solver/kinsolSolver.c:506
506       xScaling = NV_DATA_S(kinsolData->xScale);
(gdb) bt
#0  0x00007ffff789ca46 in nlsSparseJac (vecX=0xc8f2a20, vecFX=0xc8f8c20, Jac=0xc9941e0, userData=0xc8f29f0, tmp1=0xc9933e0, tmp2=0xc9933c0)
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/solver/kinsolSolver.c:506
#1  0x00007ffff789dcaf in nlsKinsolFScaling (data=0x7fffffffddc0, kinsolData=0xc8f2970, nlsData=0x7fffeeafa878, mode=SCALING_JACOBIAN)
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/solver/kinsolSolver.c:896
#2  0x00007ffff789d5bc in nlsKinsolSolve (data=0x7fffffffddc0, threadData=0x7fffffffd7e8, nlsData=0x7fffeeafa878)
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/solver/kinsolSolver.c:1189
#3  0x00007ffff78bfa1c in solveNLS (data=0x7fffffffddc0, threadData=0x7fffffffd7e8, nonlinsys=0x7fffeeafa878)
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/solver/nonlinearSystem.c:1029
#4  0x00007ffff78c0311 in solve_nonlinear_system (data=0x7fffffffddc0, threadData=0x7fffffffd7e8, sysNumber=35)
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/solver/nonlinearSystem.c:1251
#5  0x0000000000784f11 in OpenIPSL_Examples_N44_Original_Nordic44_Original_Case_eqFunction_21970 (data=0x7fffffffddc0, threadData=0x7fffffffd7e8)
    at OpenIPSL.Examples.N44.Original.Nordic44_Original_Case_06inz.c:16335
#6  0x00000000007aef0b in OpenIPSL_Examples_N44_Original_Nordic44_Original_Case_functionInitialEquations_lambda0 (data=0x7fffffffddc0, threadData=0x7fffffffd7e8)
    at OpenIPSL.Examples.N44.Original.Nordic44_Original_Case_06inz.c:39747
#7  0x00007ffff78999ca in symbolic_initialization (data=0x7fffffffddc0, threadData=0x7fffffffd7e8)
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/solver/initialization/initialization.c:379
#8  0x00007ffff78991e0 in initialization (data=0x7fffffffddc0, threadData=0x7fffffffd7e8, pInitMethod=0x7fffffffd1d0 "", pInitFile=0x7fffffffd1b0 "", initTime=0)
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/solver/initialization/initialization.c:791
#9  0x00007ffff78c82f5 in initializeModel (data=0x7fffffffddc0, threadData=0x7fffffffd7e8, init_initMethod=0x7fffffffd1d0 "", init_file=0x7fffffffd1b0 "", init_time=0)
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/solver/solver_main.c:487
#10 0x00007ffff78c9ceb in solver_main (data=0x7fffffffddc0, threadData=0x7fffffffd7e8, init_initMethod=0x7fffffffd1d0 "", init_file=0x7fffffffd1b0 "", init_time=0, solverID=8, outputVariablesAtEnd=0x0, 
    argv_0=0x7fffffffe1f6 "/mnt/home/aheuermann/workdir/Testitesttest/issue-warnComp/temp/OpenIPSL.Examples.N44.Original.Nordic44_Original_Case")
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/solver/solver_main.c:771
#11 0x00007ffff7884eb9 in callSolver (simData=0x7fffffffddc0, threadData=0x7fffffffd7e8, init_initMethod=<incomplete type>, init_file=<incomplete type>, init_time=0, 
    outputVariablesAtEnd=<incomplete type>, cpuTime=0, argv_0=0x7fffffffe1f6 "/mnt/home/aheuermann/workdir/Testitesttest/issue-warnComp/temp/OpenIPSL.Examples.N44.Original.Nordic44_Original_Case")
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/simulation_runtime.cpp:797
#12 0x00007ffff7883faa in startNonInteractiveSimulation (argc=1, argv=0x7fffffffdf58, data=0x7fffffffddc0, threadData=0x7fffffffd7e8)
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/simulation_runtime.cpp:606
#13 0x00007ffff7886fa6 in _main_SimulationRuntime (argc=1, argv=0x7fffffffdf58, data=0x7fffffffddc0, threadData=0x7fffffffd7e8)
    at /mnt/home/aheuermann/workdir/OpenModelica/OMCompiler/SimulationRuntime/c/simulation/simulation_runtime.cpp:1188
#14 0x000000000072bb8e in main (argc=1, argv=0x7fffffffdf58) at OpenIPSL.Examples.N44.Original.Nordic44_Original_Case.c:95686
```

**Comment by AnHeuermann** [comment]
Now it is not a segmentation fault any more:
```
startTime=0
stopTime=5
tolerance=5e-05
numberOfIntervals=5000
stepSize=0.001
Regular simulation: ./OpenIPSL_OpenIPSL.Examples.DAEMode.N44_Base_Case_Systems.Nordic44_Base_Case_StateEvents -abortSlowSimulation -alarm=480 -lv LOG_STATS
stdout            | info    | Using sparse solver kinsol for nonlinear system 0 (11515),
|                 | |       | because density of 0.01 remains under threshold of 0.10.
stdout            | info    | Using sparse solver kinsol for nonlinear system 52 (28245),
|                 | |       | because density of 0.01 remains under threshold of 0.10.
stdout            | info    | Using sparse solver kinsol for nonlinear system 104 (38436),
|                 | |       | because density of 0.01 remains under threshold of 0.10.
stdout            | info    | The maximum density for using sparse solvers can be specified
|                 | |       | using the runtime flag '<-nlssMaxDensity=value>'.
LOG_NLS_V         | error   | Kinsol has a serious memory issue ERROR -2
assert            | debug   | Solving non-linear system 11515 failed at time=0.
|                 | |       | For more information please use -lv LOG_NLS.
assert            | error   | Failed to solve the initialization problem with global homotopy with equidistant step size.
assert            | debug   | Unable to solve initialization problem.
assert            | info    | simulation terminated by an assertion at initialization
```

**Comment by casella** [comment]
Thanks @AnHeuermann. In my experience this kind of error often corresponds to a singular Jacobian. Whether this is due to bad start values or to structural issues in the backend, I couldn't say now. 

I guess I should try to dump the Jacoban and analyze it, looking at its nullspace. Is that possible?
